import type { CSSProperties } from "react";

export const s = {
  root: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: 14,
    padding: "0 32px",
  } satisfies CSSProperties,
  column: (accent: string): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    borderRadius: 10,
    border: "1px solid var(--border)",
    borderTopWidth: 3,
    borderTopColor: accent,
    background: "var(--bg-elevated)",
    overflow: "hidden",
  }),
  header: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  agentName: { flex: 1, minWidth: 0, fontSize: 13.5, fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  timeCost: { fontSize: 11.5, color: "var(--text-muted)" } satisfies CSSProperties,
  rows: { display: "flex", flexDirection: "column", gap: 0, maxHeight: 320, overflowY: "auto" } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 14px",
    borderBottom: "1px solid var(--border)",
    fontSize: 12.5,
  } satisfies CSSProperties,
  rowTitle: {
    flex: 1,
    minWidth: 0,
    color: "var(--text-primary)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  rowLoc: { fontSize: 11.5, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px",
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  failed: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "24px 14px",
    textAlign: "center",
    color: "var(--crit)",
  } satisfies CSSProperties,
} as const;
