import type { CSSProperties } from "react";

export const s = {
  wrap: { padding: 24, maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "baseline", gap: 10, marginBottom: 6 } satisfies CSSProperties,
  title: { fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  count: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", marginBottom: 16, lineHeight: 1.5 } satisfies CSSProperties,
  warning: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg, rgba(200,150,0,0.08))",
    color: "var(--warn)",
    fontSize: 12.5,
    lineHeight: 1.5,
    marginBottom: 14,
  } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    margin: "18px 0 8px",
  } satisfies CSSProperties,
  linkedList: { display: "flex", flexDirection: "column" } satisfies CSSProperties,
  filterInput: {
    width: "100%",
    fontSize: 13,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    outline: "none",
    marginBottom: 10,
  } satisfies CSSProperties,
  attachList: { display: "flex", flexDirection: "column" } satisfies CSSProperties,
  rowActions: { display: "flex", alignItems: "center", gap: 4 } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", padding: "8px 0" } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    marginBottom: 6,
  } satisfies CSSProperties,
  rowMain: { flex: 1, minWidth: 0, display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  rowPath: {
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "var(--font-mono, monospace)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  rowTokens: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  rowRight: { display: "flex", alignItems: "center", gap: 6, flexShrink: 0 } satisfies CSSProperties,
  previewBox: {
    padding: "10px 12px",
    marginTop: -4,
    marginBottom: 6,
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 13,
    maxHeight: 260,
    overflow: "auto",
  } satisfies CSSProperties,
  footer: {
    marginTop: 14,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 12.5,
    color: "var(--text-muted)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
} as const;
