import type { CSSProperties } from "react";

/** Co-located styles shared by ExportWizard and its four steps. */
export const s = {
  body: { padding: 24, display: "flex", flexDirection: "column", gap: 20 } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10 } satisfies CSSProperties,
  footerRight: { display: "flex", gap: 10, marginLeft: "auto" } satisfies CSSProperties,
  reason: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  repoNone: { fontSize: 12.5, color: "var(--crit)", marginTop: 6 } satisfies CSSProperties,

  // Target step
  targetGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 } satisfies CSSProperties,
  targetCard: {
    textAlign: "left",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 16,
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    cursor: "pointer",
  } satisfies CSSProperties,
  targetCardSelected: { borderColor: "var(--accent)", boxShadow: "0 0 0 1px var(--accent)" } satisfies CSSProperties,
  targetCardDisabled: { cursor: "not-allowed", opacity: 0.55 } satisfies CSSProperties,
  targetCardHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8 } satisfies CSSProperties,
  targetCardLabel: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  targetCardDesc: { fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  targetCardComingSoon: { fontSize: 11.5, fontWeight: 600, color: "var(--text-muted)" } satisfies CSSProperties,

  // Preview step
  previewLayout: { display: "grid", gridTemplateColumns: "260px 1fr", gap: 16, minHeight: 320 } satisfies CSSProperties,
  fileList: { display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  fileListHeading: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 4,
  } satisfies CSSProperties,
  fileRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 9px",
    borderRadius: 6,
    fontSize: 12.5,
    textAlign: "left",
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
    wordBreak: "break-all",
  } satisfies CSSProperties,
  fileRowSelected: {
    background: "var(--accent-bg)",
    borderColor: "var(--accent)",
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  previewPane: {
    border: "1px solid var(--border)",
    borderRadius: 9,
    background: "var(--bg-elevated)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  } satisfies CSSProperties,
  previewHeader: {
    padding: "9px 14px",
    borderBottom: "1px solid var(--border)",
    fontSize: 12.5,
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  previewContents: {
    margin: 0,
    padding: 14,
    fontSize: 12.5,
    lineHeight: 1.55,
    overflow: "auto",
    maxHeight: 420,
    whiteSpace: "pre",
    flex: 1,
  } satisfies CSSProperties,

  // Configure step
  chipRow: { display: "flex", flexWrap: "wrap", gap: 8 } satisfies CSSProperties,
  radioGroup: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  radioRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 13.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  fieldLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  callout: {
    display: "flex",
    gap: 10,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-hover)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,

  // Install step
  installCards: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  installCard: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 16,
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  installCardSelected: { borderColor: "var(--accent)", boxShadow: "0 0 0 1px var(--accent)" } satisfies CSSProperties,
  installCardDisabled: { cursor: "not-allowed", opacity: 0.55 } satisfies CSSProperties,
  installCardHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8 } satisfies CSSProperties,
  installCardTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  installCardBody: { fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  installErrorBox: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    fontSize: 12.5,
    color: "var(--crit)",
  } satisfies CSSProperties,

  // Install success view (PR link + once-only ingest token)
  successBox: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 16,
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  successTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  successBody: { fontSize: 12.5, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  tokenBox: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--warn, var(--border))",
    background: "var(--warn-bg, var(--bg-hover))",
  } satisfies CSSProperties,
  tokenValue: {
    display: "block",
    padding: "8px 10px",
    borderRadius: 6,
    background: "var(--bg-base, var(--bg-elevated))",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12.5,
    wordBreak: "break-all",
    userSelect: "all",
  } satisfies CSSProperties,
  checklistBox: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  checklist: {
    margin: 0,
    paddingLeft: 18,
    display: "flex",
    flexDirection: "column",
    gap: 4,
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
} as const;
