import type { CSSProperties } from "react";
import { LIST_COL_WIDTH } from "./constants";

export const s = {
  wrap: { display: "flex", height: "calc(100vh - 52px)" } satisfies CSSProperties,
  listCol: {
    width: LIST_COL_WIDTH,
    flexShrink: 0,
    borderRight: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  listColHead: { padding: "16px 16px 12px" } satisfies CSSProperties,
  headerRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  h1: { fontSize: 18, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  listBody: { flex: 1, overflow: "auto", padding: "0 12px 12px", display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: (active: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 4,
    width: "100%",
    textAlign: "left",
    padding: "8px 10px",
    borderRadius: 7,
    border: "1px solid " + (active ? "var(--border-strong)" : "transparent"),
    background: active ? "var(--bg-hover)" : "transparent",
    cursor: "pointer",
    font: "inherit",
    color: "var(--text-primary)",
  }),
  rowPath: {
    fontSize: 13,
    fontFamily: "var(--font-mono, monospace)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rowMeta: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  usedBy: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  footer: {
    padding: "10px 16px",
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  previewCol: { flex: 1, minWidth: 0, overflow: "auto" } satisfies CSSProperties,
  previewBody: { padding: 28, maxWidth: 860 } satisfies CSSProperties,
  truncatedNote: {
    marginBottom: 14,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  selectPrompt: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    textAlign: "center",
    padding: 28,
  } satisfies CSSProperties,
  selectPromptTitle: { fontSize: 15, fontWeight: 600, marginBottom: 6 } satisfies CSSProperties,
  selectPromptBody: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
